apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: journal-db-data-micro
  name: journal-db-data-micro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
