apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: journal-db
  name: journal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: journal-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: journal-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: journalDBMicro
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_USER
              value: journalUser
          image: mysql:8.0.40
          name: journal-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: journal-db-data-micro
      restartPolicy: Always
      volumes:
        - name: journal-db-data-micro
          persistentVolumeClaim:
            claimName: journal-db-data-micro
