apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: quarkus-reactive-service
  name: quarkus-reactive-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quarkus-reactive-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: quarkus-reactive-service
    spec:
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: mysql
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "1234"
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: vertx-reactive:mysql://journal-db:3306/journalDBMicro
            - name: QUARKUS_DATASOURCE_USERNAME
              value: journalUser
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: update
            - name: QUARKUS_HIBERNATE_ORM_LOG_SQL
              value: "true"
          image: filbon/journalsys:patientservice_journalsys-quarkus-reactive-service
          imagePullPolicy: Always
          name: quarkus-reactive-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
