apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
      nodePort: 30082  # Choose an appropriate external port for access
  selector:
    io.kompose.service: user-service
