apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://journal-db:3306/journalDBMicro
            - name: SPRING_DATASOURCE_USERNAME
              value: journalUser
          image: filbon/journalsys:patientservice_journalsys-user-service
          imagePullPolicy: Always
          name: user-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
